name = "tlrn_bot"
main = "./src/server.js"
compatibility_date="2023-05-18"

# kv_namespaces = [
#   { binding = "TLRN_TODO_ICU", id = ".." },
# ]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID